import Document, { Html, Head, Main, NextScript } from "next/document";

export default class MyDocument extends Document {
    render() {
        return (
            <Html>
                <Head>
                    <link rel="preconnect" href={`https://fonts.googleapis.com`} />
                    <link rel="shortcut icon" href="/favicon.png" type="image/png" />
                    <link
                        href={`https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap`}
                        rel="stylesheet"
                    />
                    <link
                        href={`https://fonts.googleapis.com/css2?family=M+PLUS+1+Code:wght@400;500;700&display=swap`}
                        rel="stylesheet"
                    />
                    <link
                        href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap"
                        rel="stylesheet"
                    />

                    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag@3.0.1/dist/css/multi-select-tag.css" />
                    <script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag@3.0.1/dist/js/multi-select-tag.js" />
                    <title>Cabeleleila Leila</title>
                    {/* <meta name="description" content="Generated by create next app" /> */}
                    <link rel="icon" href="/favicon.ico" />                    
                </Head>
                <body>
                    <Main />
                    <NextScript />
                </body>
            </Html>
        );
    }
}